name: Copy Artifact
on: [push]

jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Copy RPM using SSH
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - name: Copy Artifact
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_USER: ${{secrets.SSH_USER}}
        run: |
          echo "$SSH_PRIVATE_KEY" | ssh-add - < /dev/null
          ssh -i $SSH_PRIVATE_KEY -p $SSH_PORT $SSH_USER@$SSH_HOST ls          
