name: Copy Artifact
on: [push]
env:
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock
jobs:
  upload_artifact:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    name: Copy RPM using SSH
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3
      - name: Setup SSH passphrase
        env:
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          echo 'echo $SSH_PASSPHRASE' > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
      - name: Setup Host
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PORT: ${{secrets.SSH_PORT}}
          SSH_USER: ${{secrets.SSH_USER}}
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -p $SSH_PORT -t ed25519 $SSH_HOST >> ~/.ssh/known_hosts
          cat >>~/.ssh/config <<END
          Host server
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            StrictHostKeyChecking yes
          END
      - name: Setup SSH tunel
        env:
          REPO_PORT: ${{ secrets.REPO_PORT }}
        run: |
          ssh -fN -L $REPO_PORT:127.0.0.1:$REPO_PORT server
      - name: Setup Certificate
        env:
          REPO_HOST: ${{ secrets.REPO_HOST }}
          REPO_CERT: ${{ secrets.REPO_CERT }}
        run: |          
          sudo sh -c "echo '127.0.0.1 $REPO_HOST' >> /etc/hosts"
          sudo sh -c "echo '$REPO_CERT' > /usr/local/share/ca-certificates/repo.crt"
          sudo update-ca-certificates
      - name: Print ssh-add identities
        run: ssh server ls
